package mcqdeliver

import (
	"context"
	"errors"
	"fmt"
	"strconv"
	"strings"
	"testing"

	"github.com/0xGosu/herdr-auto-pilot/internal/domain"
)

// MCQResetKeysForTest mirrors the production reset burst length so the tests
// can assert on the keystrokes that follow it.
const MCQResetKeysForTest = domain.MCQResetKeys

// digitBinding is the per-tab key protocol a rendering uses. Both are real
// Claude Code behaviours, verified live 2026-07-16 against Haiku 4.5.
type digitBinding int

const (
	// digitCommits is the PLAIN rendering: the digit selects the option and
	// auto-advances to the next tab.
	digitCommits digitBinding = iota
	// digitMovesCaret is the PREVIEW rendering: the digit only moves the
	// selection caret (like ↑/↓); Enter is what commits and advances.
	digitMovesCaret
)

// fakeForm simulates a live Claude multi-tab form: N question tabs plus the
// generated Submit tab. It renders the real tab header/footer shapes so the
// production domain parser is what reads it.
type fakeForm struct {
	binding   digitBinding
	questions int
	options   int
	answered  []bool
	current   int // 0-based tab; == questions means the Submit tab
	caret     int // 1-based option under the caret
	submitted bool
	keys      []string
	failKey   string
	// submitBinding overrides binding for the Submit tab. A preview form's
	// Submit tab is generated by Claude and renders plain (audit #671).
	submitBinding digitBinding
	// multiTabs marks question tabs that are MULTI-SELECT: their options carry
	// `[ ]` checkboxes that a digit toggles, and they never auto-advance.
	multiTabs map[int]bool
	// checked[tab][option] is that tab's checkbox state.
	checked map[int]map[int]bool
	// submitStuck models a Submit tab that will not submit, so the fail-closed
	// guard for that state is reachable.
	submitStuck bool
	// toggleDeaf models a multi-select tab that swallows its digits (a build
	// with a different checkbox binding), so the toggle verification is
	// reachable. Without it, a delivery that changes nothing on screen would
	// still advance and submit an empty answer.
	toggleDeaf bool
	// hideAfterToggle drops the trailing options from a multi-select tab once
	// it has been toggled, modelling a re-render whose option list scrolls (or
	// a read window that truncates it). Verification must refuse rather than
	// skip the options it can no longer see.
	hideAfterToggle int
	// stuckTab keeps the advance key from leaving the multi-select tab.
	stuckTab bool
}

// check pre-checks a multi-select tab's option, modelling a pane that already
// carries an earlier delivery attempt's toggles.
func (f *fakeForm) check(tab, option int) {
	if f.checked[tab] == nil {
		f.checked[tab] = map[int]bool{}
	}
	f.checked[tab][option] = true
}

func newFakeForm(binding digitBinding, questions, options int) *fakeForm {
	return &fakeForm{
		binding: binding, questions: questions, options: options,
		answered: make([]bool, questions), caret: 1,
		submitBinding: digitCommits,
		multiTabs:     map[int]bool{},
		checked:       map[int]map[int]bool{},
	}
}

func (f *fakeForm) onSubmitTab() bool { return f.current == f.questions }

func (f *fakeForm) tabBinding() digitBinding {
	if f.onSubmitTab() {
		return f.submitBinding
	}
	return f.binding
}

func (f *fakeForm) SendKey(_ context.Context, _, key string) error {
	if key == f.failKey {
		return errors.New("induced keystroke failure")
	}
	f.keys = append(f.keys, key)
	if f.submitted {
		return nil // keys land in the composer once the form is gone
	}
	switch key {
	case "left":
		if f.current > 0 {
			f.current--
			f.caret = 1
		}
	case "right":
		if f.stuckTab && !f.onSubmitTab() && f.multiTabs[f.current] {
			break // the advance does not leave a multi-select tab
		}
		if f.current < f.questions {
			f.current++
			f.caret = 1
		}
	case "enter":
		f.commit()
	default:
		d, err := strconv.Atoi(key)
		if err != nil || d < 1 || d > f.options {
			break
		}
		// A multi-select tab's digit toggles a checkbox: no caret move, no
		// commit, no advance.
		if !f.onSubmitTab() && f.multiTabs[f.current] {
			if f.toggleDeaf {
				break
			}
			if f.checked[f.current] == nil {
				f.checked[f.current] = map[int]bool{}
			}
			f.checked[f.current][d] = !f.checked[f.current][d]
			break
		}
		f.caret = d
		if f.tabBinding() == digitCommits {
			f.commit()
		}
	}
	return nil
}

// commit applies the current caret selection, mirroring the real form: the
// Submit tab's option 1 submits (the form vanishes), a question tab records its
// answer and auto-advances.
func (f *fakeForm) commit() {
	if f.onSubmitTab() {
		if f.caret == 1 && !f.submitStuck {
			f.submitted = true
		}
		return
	}
	f.answered[f.current] = true
	f.current++
	f.caret = 1
}

func (f *fakeForm) Read(_ context.Context, _ string, _ int) (string, error) {
	if f.submitted {
		return "● The form was submitted. Working on it now.\n\n❯ \n", nil
	}
	var head strings.Builder
	head.WriteString("←  ")
	for i := 0; i < f.questions; i++ {
		mark := "☐"
		if f.answered[i] {
			mark = "☒"
		}
		fmt.Fprintf(&head, "%s Q%d  ", mark, i+1)
	}
	head.WriteString("✔ Submit  →")

	var b strings.Builder
	b.WriteString(head.String() + "\n\n")
	if f.onSubmitTab() {
		b.WriteString("Review your answers\n\nReady to submit your answers?\n\n")
		b.WriteString(f.renderOptions([]string{"Submit answers", "Cancel"}))
		return b.String(), nil
	}
	fmt.Fprintf(&b, "Question %d?\n\n", f.current+1)
	labels := make([]string, f.options)
	for i := range labels {
		if f.multiTabs[f.current] {
			// `[ ]`/`[x]` per option is what marks a tab multi-select on screen
			// (domain.MultiSelectTab / OptionCheckStates).
			box := "[ ]"
			if f.checked[f.current][i+1] {
				box = "[x]"
			}
			labels[i] = fmt.Sprintf("%s Option %d", box, i+1)
			continue
		}
		labels[i] = fmt.Sprintf("Option %d", i+1)
	}
	// A re-render that scrolls (or a truncated read) can show fewer options
	// than the pre-toggle read did.
	if f.hideAfterToggle > 0 && f.multiTabs[f.current] && len(f.checked[f.current]) > 0 &&
		f.hideAfterToggle < len(labels) {
		labels = labels[:f.hideAfterToggle]
	}
	b.WriteString(f.renderOptions(labels))
	b.WriteString("\n" + f.footer())
	return b.String(), nil
}

// footer mirrors the real render: the tab-switch hint appears only when there
// is a sibling question to switch to. A ONE-question form (one tab plus the
// generated Submit tab) shows the same plain footer as a single-question menu,
// which is what made it read as a plain menu and get answered with a blind
// digit that only toggled its checkbox.
func (f *fakeForm) footer() string {
	if f.questions > 1 {
		return "Enter to select · ↑/↓ to navigate · Tab to switch questions · Esc to cancel\n"
	}
	return "Enter to select · ↑/↓ to navigate · Esc to cancel\n"
}

func (f *fakeForm) renderOptions(labels []string) string {
	var b strings.Builder
	for i, label := range labels {
		caret := " "
		if f.caret == i+1 {
			caret = "❯"
		}
		fmt.Fprintf(&b, "%s %d. %s\n", caret, i+1, label)
	}
	return b.String()
}

func (f *fakeForm) config() Config {
	return Config{Keys: f, Read: f.Read, PaneID: "w1:p1", ReadLines: 40, KeyDelay: 0}
}

func groupsOf(digits ...string) [][]string {
	groups := make([][]string, len(digits))
	for i, d := range digits {
		groups[i] = []string{d}
	}
	return groups
}

// The regression this whole package exists for: on a PREVIEW form the digit
// only moves the caret, so digit-only delivery answered nothing and left the
// agent blocked. Both renderings must now land.
func TestClaudeTabsAnswersBothRenderings(t *testing.T) {
	tests := []struct {
		name    string
		binding digitBinding
		answers []string
		// wantKeys is the tail after the reset burst.
		wantKeys []string
	}{
		{
			name:    "plain rendering commits on the digit alone",
			binding: digitCommits,
			answers: []string{"2", "1", "1"},
			// No Enter: each digit already committed and advanced.
			wantKeys: []string{"2", "1", "1"},
		},
		{
			name:    "preview rendering needs Enter to commit each answer",
			binding: digitMovesCaret,
			answers: []string{"2", "1", "1"},
			// Questions need digit+Enter; the generated Submit tab is plain,
			// so its digit commits on its own.
			wantKeys: []string{"2", "enter", "1", "enter", "1"},
		},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			form := newFakeForm(tc.binding, 2, 3)
			if err := ClaudeTabs(context.Background(), form.config(), groupsOf(tc.answers...), []bool{false, false, false}); err != nil {
				t.Fatalf("ClaudeTabs returned error: %v", err)
			}
			if !form.submitted {
				t.Fatalf("form was not submitted; answered=%v current=%d", form.answered, form.current)
			}
			for i, a := range form.answered {
				if !a {
					t.Errorf("question %d was left unanswered", i+1)
				}
			}
			reset := make([]string, MCQResetKeysForTest)
			for i := range reset {
				reset[i] = "left"
			}
			want := append(reset, tc.wantKeys...)
			if strings.Join(form.keys, ",") != strings.Join(want, ",") {
				t.Errorf("keys sent =\n  %v\nwant\n  %v", form.keys, want)
			}
		})
	}
}

// A preview form's Submit tab could itself render with the caret-only binding;
// delivery must adapt there too rather than assume the digit submits.
func TestClaudeTabsAdaptsOnPreviewSubmitTab(t *testing.T) {
	form := newFakeForm(digitMovesCaret, 1, 2)
	form.submitBinding = digitMovesCaret
	if err := ClaudeTabs(context.Background(), form.config(), groupsOf("1", "1"), []bool{false, false}); err != nil {
		t.Fatalf("ClaudeTabs returned error: %v", err)
	}
	if !form.submitted {
		t.Fatal("form was not submitted")
	}
}

// Fail closed: if the digit neither commits nor moves the caret to the chosen
// option (e.g. a build unbinds digits entirely), Enter must NOT be pressed —
// it would commit whatever option the caret happens to rest on.
func TestClaudeTabsRefusesWhenCaretDidNotReachOption(t *testing.T) {
	form := newFakeForm(digitMovesCaret, 2, 3)
	form.options = 0 // digits are ignored entirely: caret never moves
	err := ClaudeTabs(context.Background(), form.config(), groupsOf("2", "1", "1"), []bool{false, false, false})
	if err == nil {
		t.Fatal("expected an error when the caret never reached the chosen option")
	}
	if !strings.Contains(err.Error(), "was not selected") {
		t.Errorf("error = %v, want it to name the unselected option", err)
	}
	for _, k := range form.keys {
		if k == "enter" {
			t.Fatal("Enter must not be pressed once the caret is known to be wrong")
		}
	}
	if form.answered[0] {
		t.Error("no answer should have been committed")
	}
}

// A multi-select tab toggles checkboxes (previews and multi-select are mutually
// exclusive, so it is always the plain digit-toggling rendering) and does not
// auto-advance, so it keeps its explicit advance key.
func TestClaudeTabsTogglesAndAdvancesMultiSelectTab(t *testing.T) {
	form := newFakeForm(digitCommits, 1, 3)
	form.multiTabs[0] = true
	err := ClaudeTabs(context.Background(), form.config(),
		[][]string{{"1", "3"}, {"1"}}, []bool{true, false})
	if err != nil {
		t.Fatalf("ClaudeTabs returned error: %v", err)
	}
	tail := form.keys[MCQResetKeysForTest:]
	want := []string{"1", "3", "right", "1"}
	if strings.Join(tail, ",") != strings.Join(want, ",") {
		t.Errorf("keys = %v, want %v", tail, want)
	}
	// The keystrokes must actually have toggled the chosen options — asserting
	// only the key list passes even when every toggle is a no-op.
	if got := form.checked[0]; !got[1] || !got[3] || got[2] {
		t.Errorf("checked = %v, want options 1 and 3 checked and 2 untouched", got)
	}
	if !form.submitted {
		t.Error("the form should still have been submitted after the multi-select tab")
	}
}

// The retry regression (audit #41-#44, 2026-07-20): a digit TOGGLES a checkbox,
// so a second delivery attempt over a pane that already carries the first
// attempt's toggles must not press it again — that would CLEAR the selection
// and submit an empty answer while every keystroke looked delivered. A retry
// has to be idempotent: press nothing, verify, advance.
func TestClaudeTabsDoesNotRetoggleAlreadyChosenOptions(t *testing.T) {
	form := newFakeForm(digitCommits, 1, 3)
	form.multiTabs[0] = true
	form.check(0, 1) // the previous attempt already checked option 1
	form.check(0, 3)

	err := ClaudeTabs(context.Background(), form.config(),
		[][]string{{"1", "3"}, {"1"}}, []bool{true, false})
	if err != nil {
		t.Fatalf("ClaudeTabs returned error: %v", err)
	}
	tail := form.keys[MCQResetKeysForTest:]
	want := []string{"right", "1"} // no toggles: advance, then Submit
	if strings.Join(tail, ",") != strings.Join(want, ",") {
		t.Errorf("keys = %v, want %v (the chosen options must not be re-pressed)", tail, want)
	}
	if got := form.checked[0]; !got[1] || !got[3] {
		t.Errorf("checked = %v, want options 1 and 3 still checked", got)
	}
	if !form.submitted {
		t.Error("the retry should have submitted the form")
	}
}

// A partially-delivered tab (the first attempt died between its two toggles)
// must be completed, not restarted: press only the missing option.
func TestClaudeTabsPressesOnlyTheMissingOptions(t *testing.T) {
	form := newFakeForm(digitCommits, 1, 3)
	form.multiTabs[0] = true
	form.check(0, 1)

	err := ClaudeTabs(context.Background(), form.config(),
		[][]string{{"1", "3"}, {"1"}}, []bool{true, false})
	if err != nil {
		t.Fatalf("ClaudeTabs returned error: %v", err)
	}
	tail := form.keys[MCQResetKeysForTest:]
	want := []string{"3", "right", "1"}
	if strings.Join(tail, ",") != strings.Join(want, ",") {
		t.Errorf("keys = %v, want %v", tail, want)
	}
	if got := form.checked[0]; !got[1] || !got[3] {
		t.Errorf("checked = %v, want options 1 and 3 checked", got)
	}
	if !form.submitted {
		t.Error("the form should have been submitted")
	}
}

// A checkbox this answer did not choose is someone else's selection. Clearing
// it would be the same blind toggle, so delivery refuses before pressing
// anything — the frontend's capture-time rule, enforced at the keystroke.
func TestClaudeTabsRefusesForeignSelection(t *testing.T) {
	form := newFakeForm(digitCommits, 1, 3)
	form.multiTabs[0] = true
	form.check(0, 2)

	err := ClaudeTabs(context.Background(), form.config(),
		[][]string{{"1"}, {"1"}}, []bool{true, false})
	if err == nil {
		t.Fatal("ClaudeTabs accepted a tab carrying a selection it did not choose")
	}
	if !strings.Contains(err.Error(), "option(s) 2") {
		t.Errorf("error = %v, want it to name the foreign selection", err)
	}
	if tail := form.keys[MCQResetKeysForTest:]; len(tail) != 0 {
		t.Errorf("keys = %v, want none: the refusal must precede every keystroke", tail)
	}
	if form.submitted {
		t.Error("the form must not have been submitted")
	}
}

// Toggles that do not land must fail closed. Without this the advance would
// move on and Submit would commit an EMPTY answer — delivered, audited, wrong.
func TestClaudeTabsRefusesWhenTogglesDoNotLand(t *testing.T) {
	form := newFakeForm(digitCommits, 1, 3)
	form.multiTabs[0] = true
	form.toggleDeaf = true

	err := ClaudeTabs(context.Background(), form.config(),
		[][]string{{"1"}, {"1"}}, []bool{true, false})
	if err == nil {
		t.Fatal("ClaudeTabs reported success though no checkbox changed")
	}
	if !strings.Contains(err.Error(), "did not land") {
		t.Errorf("error = %v, want it to name the unlanded toggle", err)
	}
	if form.submitted {
		t.Error("an unverified toggle must never reach Submit")
	}
}

// Verification must fail CLOSED when an option stops being readable: skipping
// the options the post-toggle re-render no longer shows would advance having
// pressed a toggle nothing confirmed.
func TestClaudeTabsRefusesWhenOptionsBecomeUnreadable(t *testing.T) {
	form := newFakeForm(digitCommits, 1, 3)
	form.multiTabs[0] = true
	form.hideAfterToggle = 1 // only option 1 survives the re-render

	err := ClaudeTabs(context.Background(), form.config(),
		[][]string{{"1"}, {"1"}}, []bool{true, false})
	if err == nil {
		t.Fatal("ClaudeTabs accepted a selection it could not fully verify")
	}
	if !strings.Contains(err.Error(), "can not verify") {
		t.Errorf("error = %v, want it to say the selection could not be verified", err)
	}
	if !strings.Contains(err.Error(), "option(s) 1 were pressed") {
		t.Errorf("error = %v, want it to name the keys it already sent", err)
	}
	if form.submitted {
		t.Error("an unverified selection must never reach Submit")
	}
}

// The advance is verified too: a multi-select tab that does not move on would
// otherwise have its next tab's answer typed into it.
func TestClaudeTabsRefusesWhenMultiSelectTabDoesNotAdvance(t *testing.T) {
	form := newFakeForm(digitCommits, 2, 3)
	form.multiTabs[0] = true
	form.stuckTab = true

	err := ClaudeTabs(context.Background(), form.config(),
		[][]string{{"1"}, {"1"}, {"1"}}, []bool{true, false, false})
	if err == nil {
		t.Fatal("ClaudeTabs reported success though the tab never advanced")
	}
	if !strings.Contains(err.Error(), "did not advance") {
		t.Errorf("error = %v, want it to name the stuck advance", err)
	}
	if form.submitted {
		t.Error("the form must not have been submitted")
	}
}

// An answer naming an option the tab does not offer is refused before any
// keystroke — a digit outside the option set would toggle nothing, or worse.
func TestClaudeTabsRefusesUnofferedMultiSelectOption(t *testing.T) {
	form := newFakeForm(digitCommits, 1, 2)
	form.multiTabs[0] = true

	err := ClaudeTabs(context.Background(), form.config(),
		[][]string{{"3"}, {"1"}}, []bool{true, false})
	if err == nil {
		t.Fatal("ClaudeTabs accepted an option the tab does not offer")
	}
	if !strings.Contains(err.Error(), "does not offer option 3") {
		t.Errorf("error = %v, want it to name the missing option", err)
	}
	if tail := form.keys[MCQResetKeysForTest:]; len(tail) != 0 {
		t.Errorf("keys = %v, want none before the refusal", tail)
	}
}

// A tab flagged multi-select whose options carry no checkboxes is not the
// rendering this branch answers; toggling it blind would press digits into a
// single-select menu.
func TestClaudeTabsRefusesMultiSelectFlagOnPlainTab(t *testing.T) {
	form := newFakeForm(digitCommits, 1, 3) // no multiTabs entry: plain options

	err := ClaudeTabs(context.Background(), form.config(),
		[][]string{{"1"}, {"1"}}, []bool{true, false})
	if err == nil {
		t.Fatal("ClaudeTabs toggled a tab that shows no checkboxes")
	}
	if !strings.Contains(err.Error(), "not multi-select") {
		t.Errorf("error = %v, want it to report the missing checkboxes", err)
	}
	if tail := form.keys[MCQResetKeysForTest:]; len(tail) != 0 {
		t.Errorf("keys = %v, want none before the refusal", tail)
	}
}

// A tab that is ALREADY answered (☒ — an operator got there first; the sweep
// counts such tabs and does not refuse them) is the trap the tab-identity gate
// exists for. Pressing its digit RE-answers it and auto-advances, so the
// unanswered count does not move — indistinguishable by count alone from the
// preview rendering's caret-only digit. Committing there would answer the NEXT
// question with this tab's digit, and the count would then drop by one, so it
// would even look like it worked. Delivery must refuse instead.
func TestClaudeTabsRefusesAlreadyAnsweredTab(t *testing.T) {
	form := newFakeForm(digitCommits, 2, 3)
	form.answered[0] = true // tab 1 renders ☒ before delivery starts

	err := ClaudeTabs(context.Background(), form.config(), groupsOf("1", "2", "1"), []bool{false, false, false})
	if err == nil {
		t.Fatal("expected delivery to refuse a form whose first tab is already answered")
	}
	if !strings.Contains(err.Error(), "moved to another question") {
		t.Errorf("error = %v, want it to report the form moving tabs", err)
	}
	if form.answered[1] {
		t.Error("question 2 must not be answered with question 1's digit")
	}
	if form.submitted {
		t.Error("the form must not be submitted after a refusal")
	}
}

// The Submit tab is single-select — its digit submits. Flagging it multi-select
// would toggle-and-advance and report success while submitting nothing: the
// exact silent no-op this package exists to prevent.
func TestClaudeTabsRefusesMultiSelectSubmitTab(t *testing.T) {
	form := newFakeForm(digitCommits, 1, 2)
	err := ClaudeTabs(context.Background(), form.config(), [][]string{{"1"}, {"1"}}, []bool{false, true})
	if err == nil {
		t.Fatal("expected delivery to refuse a multi-select Submit tab")
	}
	if !strings.Contains(err.Error(), "Submit tab") {
		t.Errorf("error = %v, want it to name the Submit tab", err)
	}
	if form.submitted {
		t.Error("nothing should have been submitted")
	}
}

// A Submit tab that does not submit must surface, not report success.
func TestClaudeTabsRefusesWhenSubmitDoesNotSubmit(t *testing.T) {
	form := newFakeForm(digitCommits, 1, 2)
	form.submitStuck = true
	err := ClaudeTabs(context.Background(), form.config(), groupsOf("1", "1"), []bool{false, false})
	if err == nil || !strings.Contains(err.Error(), "did not submit") {
		t.Fatalf("error = %v, want the stuck Submit tab to surface", err)
	}
}

// The live form having a different tab count than the answer was built for must
// fail closed inside the package, not rely on the caller's earlier check.
func TestClaudeTabsRefusesTabCountMismatch(t *testing.T) {
	form := newFakeForm(digitCommits, 3, 2) // 3 questions + Submit = 4 tabs
	err := ClaudeTabs(context.Background(), form.config(), groupsOf("1", "1"), []bool{false, false})
	if err == nil || !strings.Contains(err.Error(), "tabs") {
		t.Fatalf("error = %v, want a tab-count mismatch refusal", err)
	}
	if form.answered[0] {
		t.Error("nothing should have been answered")
	}
}

// A keystroke failure must surface rather than be silently swallowed.
func TestClaudeTabsPropagatesKeystrokeFailure(t *testing.T) {
	form := newFakeForm(digitMovesCaret, 2, 3)
	form.failKey = "enter"
	err := ClaudeTabs(context.Background(), form.config(), groupsOf("1", "1", "1"), []bool{false, false, false})
	if err == nil {
		t.Fatal("expected the induced Enter failure to surface")
	}
	if !strings.Contains(err.Error(), "commit") {
		t.Errorf("error = %v, want it to name the failing commit step", err)
	}
}

// The form vanishing mid-series (replaced, or the agent moved on) must fail
// closed instead of pressing the remaining answers into whatever is now there.
func TestClaudeTabsRefusesWhenFormDisappearsEarly(t *testing.T) {
	form := newFakeForm(digitCommits, 2, 3)
	form.submitted = true // nothing on screen resembles the form
	err := ClaudeTabs(context.Background(), form.config(), groupsOf("1", "1", "1"), []bool{false, false, false})
	if err == nil {
		t.Fatal("expected an error when the form is not showing")
	}
	if !strings.Contains(err.Error(), "no longer showing") {
		t.Errorf("error = %v, want it to report the missing form", err)
	}
}

// A read failure fails closed too.
func TestClaudeTabsPropagatesReadFailure(t *testing.T) {
	form := newFakeForm(digitCommits, 1, 2)
	cfg := form.config()
	cfg.Read = func(context.Context, string, int) (string, error) {
		return "", errors.New("induced read failure")
	}
	err := ClaudeTabs(context.Background(), cfg, groupsOf("1", "1"), []bool{false, false})
	if err == nil || !strings.Contains(err.Error(), "induced read failure") {
		t.Fatalf("error = %v, want the induced read failure", err)
	}
}
