#!/usr/bin/env bash
# Devcontainer post-create setup for hap development.
#
# Runs once after the container is created (invoked from
# .devcontainer/devcontainer.json's postCreateCommand). Keep every step
# idempotent — a rebuilt container re-runs this.
#
#   - libopenblas-dev: FAISS's BLAS backend — the runtime libopenblas.so.0 the
#     CGO-linked binary and `go test -tags "vectors cpu"` load at startup, AND
#     the headers + unversioned libopenblas.so scripts/setup-native.sh needs to
#     build FAISS from source. It must be the -dev package: setup-native.sh
#     skips its own libopenblas-dev install whenever ldconfig already lists
#     libopenblas, so pre-seeding only the runtime libopenblas0 here left the
#     FAISS build without a BLAS it could link.
#   - cmake: the build driver scripts/setup-native.sh uses for llama.cpp and
#     FAISS. That script installs it on demand, but pre-seeding it here keeps
#     the first native build from stopping to apt-install mid-run.
#   - golangci-lint: pinned to the release CI runs (.github/workflows/ci.yml),
#     behind a wrapper that runs it under the Go toolchain it was BUILT with.
#     The image's Go can be newer than that (the trixie image ships go1.27),
#     and a linter older than the stdlib it loads cannot typecheck it: the
#     release binary reports two `typecheck` errors in crypto/internal/randutil
#     and the whole-program `unused` linter then silently reports nothing, while
#     a copy rebuilt with the newer Go panics in staticcheck's IR builder. The
#     toolchain is read from the binary itself, so bumping the version below
#     needs no other edit. HAP_LINT_GOTOOLCHAIN overrides it.
#
# Native libs (llama.cpp, FAISS) are NOT installed here — run
# `bash scripts/setup-native.sh` once before `go build -tags "vectors cpu"`.
set -euo pipefail

# Only apt-based images have these packages; skip quietly elsewhere.
if command -v apt-get >/dev/null 2>&1; then
  SUDO=""
  [ "$(id -u)" -eq 0 ] || SUDO="sudo"
  PKGS=()
  dpkg-query -W -f='${Status}' libopenblas-dev 2>/dev/null | grep -q 'install ok installed' ||
    PKGS+=(libopenblas-dev)
  command -v cmake >/dev/null 2>&1 || PKGS+=(cmake)
  if [ "${#PKGS[@]}" -gt 0 ]; then
    echo "==> installing ${PKGS[*]}"
    $SUDO apt-get update -qq
    $SUDO apt-get install -y -qq "${PKGS[@]}"
  fi
fi

# Keep in step with golangci-lint-action's `version:` in .github/workflows/ci.yml.
GOLANGCI_LINT_VERSION="v2.12.2"
GOBIN_DIR="$(go env GOPATH)/bin"
GOLANGCI_LINT_REAL_DIR="$(go env GOPATH)/lib/golangci-lint-$GOLANGCI_LINT_VERSION"
GOLANGCI_LINT_REAL="$GOLANGCI_LINT_REAL_DIR/golangci-lint"
GOLANGCI_LINT_WRAPPER="$GOBIN_DIR/golangci-lint"

if [ ! -x "$GOLANGCI_LINT_REAL" ] ||
  ! "$GOLANGCI_LINT_REAL" version 2>/dev/null | grep -Fq "has version ${GOLANGCI_LINT_VERSION#v} "; then
  echo "==> installing golangci-lint $GOLANGCI_LINT_VERSION"
  mkdir -p "$GOLANGCI_LINT_REAL_DIR"
  curl -sSfL https://golangci-lint.run/install.sh |
    sh -s -- -b "$GOLANGCI_LINT_REAL_DIR" "$GOLANGCI_LINT_VERSION"
fi

LINT_GOTOOLCHAIN="$("$GOLANGCI_LINT_REAL" version 2>/dev/null |
  sed -n 's/.* built with \(go[0-9][0-9.]*\) .*/\1/p')"
if [ -z "$LINT_GOTOOLCHAIN" ]; then
  echo "cannot read the Go toolchain golangci-lint $GOLANGCI_LINT_VERSION was built with" >&2
  exit 1
fi

# Rewritten every run (it is cheap) so a version bump always re-points it.
mkdir -p "$GOBIN_DIR"
cat >"$GOLANGCI_LINT_WRAPPER" <<EOF
#!/bin/sh
# Generated by scripts/devcontainer-postcreate.sh — edits are overwritten.
# Runs golangci-lint $GOLANGCI_LINT_VERSION under the Go toolchain it was built
# with; a newer stdlib makes it report spurious typecheck errors and silently
# drop the \`unused\` linter. Override with HAP_LINT_GOTOOLCHAIN.
GOTOOLCHAIN="\${HAP_LINT_GOTOOLCHAIN:-$LINT_GOTOOLCHAIN}" exec "$GOLANGCI_LINT_REAL" "\$@"
EOF
chmod +x "$GOLANGCI_LINT_WRAPPER"

# Fetch the pinned toolchain now, so the first lint neither stalls on the
# download nor fails offline.
echo "==> fetching Go toolchain $LINT_GOTOOLCHAIN for golangci-lint"
GOTOOLCHAIN="$LINT_GOTOOLCHAIN" go version

echo "devcontainer post-create setup complete"
